<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-6FQI5GQB" failures="6" tests="11" name="Test" time="8.226" errors="0" timestamp="2022-04-15T10:25:41 ICT">
  <testcase classname="TaiKhoanTest" name="addUser" time="0.872"/>
  <testcase classname="TaiKhoanTest" name="deleteUser" time="0.434"/>
  <testcase classname="TaiKhoanTest" name="findUserByUserName" time="0.081">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TaiKhoanTest.findUserByUserName(TaiKhoanTest.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- findUserByUserName -->
  <testcase classname="TaiKhoanTest" name="updateUser" time="1.043"/>
  <testcase classname="PhongTest" name="addUser" time="0.539">
    <failure type="java.lang.NumberFormatException" message="empty String">
      <![CDATA[java.lang.NumberFormatException: empty String
at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
at java.base/java.lang.Float.parseFloat(Float.java:476)
at java.base/java.lang.Float.valueOf(Float.java:440)
at PhongTest.addUser(PhongTest.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- addUser -->
  <testcase classname="PhongTest" name="deleteRoom" time="0.177">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint &amp;quot;FK_ThanhToan_DatPhong&amp;quot;. The conflict occurred in database &amp;quot;GFTHotel&amp;quot;, table &amp;quot;dbo.ThanhToan&amp;quot;, column &amp;apos;MaDP&amp;apos;.">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_ThanhToan_DatPhong". The conflict occurred in database "GFTHotel", table "dbo.ThanhToan", column 'MaDP'.
at utils.JDBCHelper.update(JDBCHelper.java:58)
at dao.PhongDAO.delete(PhongDAO.java:39)
at PhongTest.deleteRoom(PhongTest.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_ThanhToan_DatPhong". The conflict occurred in database "GFTHotel", table "dbo.ThanhToan", column 'MaDP'.
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:232)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1672)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:460)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:405)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7535)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2438)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:208)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:183)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:348)
at utils.JDBCHelper.update(JDBCHelper.java:53)
... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- deleteRoom -->
  <testcase classname="PhongTest" name="updateRoom" time="0.075">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;entity.Phong.setTenPhong(String)&amp;quot; because &amp;quot;phong&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "entity.Phong.setTenPhong(String)" because "phong" is null
at PhongTest.updateRoom(PhongTest.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- updateRoom -->
  <testcase classname="NhanVienTest" name="addUser" time="0.855"/>
  <testcase classname="NhanVienTest" name="delete" time="0.155"/>
  <testcase classname="NhanVienTest" name="findUserByUserName" time="0.05">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at NhanVienTest.findUserByUserName(NhanVienTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- findUserByUserName -->
  <testcase classname="NhanVienTest" name="updateUser" time="0.037">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;String.equals(Object)&amp;quot; because &amp;quot;HoTen&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "HoTen" is null
at NhanVienTest.checkAddUser(NhanVienTest.java:32)
at NhanVienTest.updateUser(NhanVienTest.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- updateUser -->
</testsuite> <!-- Test -->
